out_dir: tests/results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: peptides-struct
  entity: tum_i26
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: s2gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 3
  dim_inner: 235
  layer_type: gcnconv
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.1
  agg: mean
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
share:
  dim_in: 235
device: cuda
