out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: arxiv-year
  entity: tum_i26
dataset:
  format: OGB
  name: arxiv-year
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: OGBNArxivLinearNode
  node_encoder_bn: False
  edge_encoder: False
  ogbn_arxiv:
    mask_rate: ~
    use_labels: False
  arxiv_year:
    num_split: 0
    with_ogbn_arxiv_labels: False
posenc_MagLapPE:
  enable: False
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch', 'train_mask', 'val_mask', 'test_mask']
model:
  type: s2gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: transductive_node
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 256
  layer_type: lin_gnn
  residual: False
  stage_type: stack
  act: relu
  dropout: 0.5
  agg: mean
  adj_norm: gcn
  dir_aggr: mean
  make_undirected: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.005
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
device: cuda