out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: arxiv-year
  entity: tum_i26
dataset:
  format: OGB
  name: arxiv-year
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: OGBNArxivLinearNode+MagLapPE
  node_encoder_bn: False
  edge_encoder: False
  ogbn_arxiv:
    mask_rate: ~
    use_labels: False
  arxiv_year:
    num_split: 0
    with_ogbn_arxiv_labels: False
posenc_MagLapPE:
  enable: True
  precompute: True
  q: 0.0001
  largest_connected_component: False
  positional_encoding: False
  window: tukey
  max_freqs: 100
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch', 'train_mask', 'val_mask', 'test_mask']
model:
  type: s2gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: transductive_node
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 1
  dim_inner: 256
  layer_type: lin_gnn
  residual: False
  stage_type: stack
  act: relu
  dropout: 0.5
  agg: mean
  adj_norm: gcn
  dir_aggr: mean
  make_undirected: False
  spectral:
    layer_skip: [0, 3]
    residual: True
    dropout: 0.5
    filter_encoder: basis
    filter_value_trans: ~
    frequency_cutoff: 0.017
    # drop_trailing_repeated: True
    feature_transform: ~
    filter_variant: silu_mix
    # basis_init_type: zeros
    num_heads_filter_encoder:  -1
    basis_bottleneck: 0.05
    basis_num_gaussians: 50
    learnable_norm: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.005
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
device: cuda