out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: associative-recall
  entity: tum_i26
dataset:
  format: synthetic
  name: associative-recall
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode+MagLapPE
  node_encoder_bn: False
  edge_encoder: False
posenc_MagLapPE:
  enable: True
  q: 0.0001
  largest_connected_component: False
  positional_encoding: True
  dim_pe: 8
  max_freqs: 10
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch']
model:
  type: s2gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: masked_readout_graph
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 2
  dim_inner: 224
  layer_type: lin_gnn
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.1
  agg: mean
  make_undirected: False
  l2norm: False
  residual: True
  layer_skip: []
  spectral:
    layer_skip: []
    residual: True
    filter_encoder: basis
    frequency_cutoff: 4
    feature_transform: glu
    filter_variant: silu_mix
    filter_layers: 1
    filter_value_trans: nacos
    basis_bottleneck: 0.2
    window: exp
    basis_num_gaussians: 30
    num_heads_filter_encoder: 224
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.001
  base_lr: 0.01
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
share:
  dim_in: 224
device: cuda