out_dir: tests/results
metric_best: mae
metric_agg: argmin
num_workers: 6
wandb:
  use: True
  project: pcqm4m
  entity: tum_i26
dataset:
  format: OGB
  name: PCQM4Mv2-full
  task: graph
  task_type: regression
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+MagLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
posenc_MagLapPE:
  enable: True
  precompute: True
  positional_encoding: True
  dim_pe: 16
  q: 0.
  largest_connected_component: False
  sparse: False
  max_freqs: 52
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_best: True
model:
  type: s2gnn
  loss_fun: l1
  graph_pooling: mean
  edge_decoding: dot
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_mp: 5
  layers_post_mp: 3
  dim_inner: 304
  layer_type: gatedgcnconv
  act: gelu
  residual: True
  dropout: 0.2
  batchnorm: False
  spectral:
    layer_skip: [-1]
    frequency_cutoff: 0.8
    filter_encoder: basis
    feature_transform: glu_0.05
    filter_variant: None
    window: tukey
    basis_num_gaussians: 60
    basis_bottleneck: 1.
    num_heads_filter_encoder: 128
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
share:
  dim_in: 304
device: cuda
