out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: ogbn-products
  entity: tum_i26
dataset:
  format: OGB
  name: ogbn-products
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: OGBNArxivNode
  edge_encoder: False
  ogbn_arxiv:
    mask_rate: ~
    use_labels: True
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch', 'train_mask', 'val_mask', 'test_mask']
model:
  type: s2gnn
  loss_fun: cross_entropy_ogbn-arxiv
gnn:
  head: transductive_node
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 0
  dim_inner: 256
  layer_type: lin_gnn
  node_dropout: 0.25
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.5
  agg: mean
  adj_norm: gcn
  residual: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.  #1e-4
  base_lr: 0.0005  #0.005
  max_epoch: 1_000
  scheduler: constant_with_warmup  # cosine_with_warmup
  num_warmup_epochs: 10
device: cuda
