out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: ogbn-products
  entity: tum_i26
dataset:
  format: OGB
  name: ogbn-products
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: OGBNArxivNode
  edge_encoder: False
  ogbn_arxiv:
    mask_rate: ~
    use_labels: True
posenc_MagLapPE:
  enable: False
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch', 'train_mask', 'val_mask', 'test_mask']
  sampler: random_node
  train_parts: 16
model:
  type: s2gnn
  loss_fun: cross_entropy_ogbn-arxiv
gnn:
  head: transductive_node
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 1
  dim_inner: 256
  layer_type: gatconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.5
  agg: mean
  adj_norm: gcn
  residual: True
  gatconv:
    pre_dropout: 0.15
    num_heads: 8
    negative_slope: 0.2
    attn_dropout: 0.05
    feat_dropout: 0.5
    norm: False
    backend: PyG
    with_linear: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 400
  scheduler: constant_with_warmup
  num_warmup_epochs: 20
device: cuda
