out_dir: tests/results
metric_best: accuracy
wandb:
  use: True
  project: ogbn-products
  entity: tum_i26
dataset:
  format: OGB
  name: ogbn-products
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: OGBNArxivNode
  edge_encoder: False
  ogbn_arxiv:
    mask_rate: ~
    use_labels: True
posenc_MagLapPE:
  enable: True
  q: 0.0
  frequency_cutoff: 0.004
  largest_connected_component: False
  precompute: True
  max_freqs: 50
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch', 'train_mask', 'val_mask', 'test_mask']
model:
  type: s2gnn
  loss_fun: cross_entropy_ogbn-arxiv
gnn:
  head: transductive_node
  layers_pre_mp: 1
  layers_mp: 1
  layers_post_mp: 1
  dim_inner: 256
  layer_type: lin_gnn
  layer_skip: [0]
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.5
  agg: mean
  adj_norm: gcn
  residual: False
  spectral:
    layer_skip: []
    filter_encoder: basis
    # drop_trailing_repeated: True
    feature_transform: ~  #glu
    filter_variant: lin
    basis_bottleneck: 0.1
    largest_connected_component: True
    num_heads_filter_encoder: -1
    basis_num_gaussians: 50
    learnable_norm: True
    window: tukey
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.01
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 20
device: cuda
