out_dir: tests/results
metric_best: accuracy-SBM
wandb:
  use: True
  project: cluster
  entity: tum_i26
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CLUSTER
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode+MagLapPE
  node_encoder_bn: False
  edge_encoder: False
posenc_MagLapPE:
  enable: True
  q: 0.0
  largest_connected_component: False
  positional_encoding: True
  max_freqs: 50
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch']
model:
  type: s2gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 16
  layers_post_mp: 2
  dim_inner: 78
  layer_type: gatedgcnconv
  residual: True
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.0
  agg: mean
  spectral:
    layer_skip: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
device: cuda