out_dir: tests/results
metric_best: accuracy-SBM
wandb:
  use: True
  project: cluster
  entity: tum_i26
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CLUSTER
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: False
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_best: True
  ckpt_data_splits: ['val', 'test']
  ckpt_data_attrs: ['y', 'pred', 'batch']
model:
  type: s2gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 16
  layers_post_mp: 2
  dim_inner: 176
  layer_type: gatconv
  DROP_spec_layer_type: ~
  residual: True
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.0
  agg: mean
  gatconv:
    pre_dropout: 0.0
    num_heads: 8
    negative_slope: 0.2
    attn_dropout: 0.0
    feat_dropout: 0.0
    norm: True
    backend: PyG
    with_linear: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
device: cuda